### PR TITLE
[docs] collection of minor pet-peeves

### PR DESCRIPTION
**Pull request by gautambaghel**

### CODE REVIEW

**Review by danbarr — CHANGES_REQUESTED** [review]
Love a good nitpick PR 😄 
But one back at you - we don't actually capitalize "agent" per our style guide (capitalize products but not features). The docs are a bit mixed on this when it's the full "Terraform Cloud Agent" name but the agents tutorial has the more updated styling.

**Comment by gautambaghel** [comment]
Good to know!

**Review by danbarr — APPROVED** [review]
LGTM!

**Comment by danbarr** [comment]
OK, **now** it LGTM 😉

**Pull request merged**
